name: CI

on:
  pull_request:
    branches: [main]
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Integration Tests
        run: npm run test

      - name: E2E Tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run start
          wait-on: http://localhost:3000
